name: Deploy Microservices to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Images
        run: |
          services=("api-gateway" "appointment-service" "auth-service" "billing-service" "patient-service" "analytics-service")
          for service in "${services[@]}"; do
            echo "Building $service..."
            docker build -t $service ./\$service
            docker tag $service:latest ${{ steps.login-ecr.outputs.registry }}/${service}:latest
            docker push ${{ steps.login-ecr.outputs.registry }}/${service}:latest
          done

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file infrastructure/cdk.out/localstack.template.json \
            --stack-name patient-management-stack \
            --capabilities CAPABILITY_IAM
